name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - ci
    tags:
      - lighttpd-*

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

jobs:

  Windows-Cygwin:
    runs-on: windows-latest
    env:
      CYGWIN: winsymlinks:native
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4

      - name: Set up env and create cache dir
        shell: pwsh
        id: env
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "CACHE_KEY=$(Get-Date -UFormat "%Y-%m")" -Encoding utf8NoBOM
          mkdir D:\cygwin

      - name: Cache Cygwin installation and packages
        uses: actions/cache@v3
        with:
          path: /cygwin
          key: cygwin-${{ runner.os }}-${{ env.CACHE_KEY }}
          restore-keys: |
            cygwin-${{ runner.os }}-${{ env.CACHE_KEY }}

      - name: Create Cygwin package cache dir
        shell: pwsh
        run: |
          New-Item -Path D:\cygwin\packages -ItemType Directory -Force
          New-Item -ItemType SymbolicLink -Path D:\cygwin-packages -Target D:\cygwin\packages
          #cmd /c mklink /d D:\cygwin-packages D:\cygwin\packages

      - uses: cygwin/cygwin-install-action@master
        with:
          install-dir: D:\cygwin
          allow-test-packages: true
          packages: >
            autoconf automake libtool m4 make
            cmake meson ninja scons
            gcc-g++ git pkgconf perl
            libpcre2-devel
            libnettle-devel
            libgnutls-devel mbedtls-devel libnss-devel libssl-devel
            libbrotli-devel libdeflate-devel zlib-devel libzstd-devel
            libsasl2-devel libkrb5-devel libdbi-devel openldap-devel
            libmariadb-devel libpq-devel
            libmaxminddb-devel libunwind-devel lua-devel lua5.1-devel
            libxml2-devel libsqlite3-devel
            libintl-devel
      - name: Compile and Test
        shell: D:\cygwin\bin\bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
        run: |
          set -e
          export PATH=/usr/bin:$(cygpath ${SYSTEMROOT})/system32
          export NO_PAM=1 NO_UNWIND=1 NO_WOLFSSL=1
          export SHELL=/bin/dash
          cd "${{github.workspace}}" && /bin/dash scripts/ci-build.sh autobuild
